  ---
- hosts: ws
  become: 1
  gather_facts: 1
  ignore_errors: True
  vars:
     user_name: serge2026
     group: terraform 

  tasks:
    - name: check server uptime
      command: uptime
    - name: list directory
      shell: ls
    - name: check the kernel version
      command: uname -r
    - name: create user
      user:
        name: "{{user_name}}"
    - name: create group
      group:
        name: "{{group}}"
